### ISSUE TITLE
Controls funktionieren nicht

### ISSUE THREAD

**Issue by Alacant** [TheVaan/Rawr-RG#11]
Sobald Lokalisierungen in den Formeigenschaften eingestellt wird, funktionieren bspw. der ItemComparisonGraph oder die Buttons für MainHand, Offhand etc. nicht mehr richtig. (Leisten bleiben nicht mehr innerhalb der maximalen Breite, Buttons sind verschwunden, keine Scrollbars vorhanden.)

Ursache konnte ich bisher noch nicht feststellen. Sollte nochmal beobachtet werden, daher bleibt die Lokalisierung erstmal aus.

PS: btw. habe ich wohl doch nicht genügend Rechte um zu mergen, Issues zuzuweisen etc. :octocat:

**Comment by Alacant** [comment]
Fixed. Das Size-Attribut der Controls wurde neu beschrieben.

**Comment by TheVaan** [comment]
Hab dir den Invite Link mal per PN im RG Forum geschickt... komischer Mist hier.
